### ISSUE TITLE
Excluding files and directories when using this action

### ISSUE THREAD

**Issue by joachimesque** [greut/eclint-action#1]
Hi!

The doc for `eclint` says that we can exclude files from the linter. Is there a way to do it in the Github Action?

**Comment by szepeviktor** [comment]
@greut Could you add an action parameter that passes on `eclint` command line options?

**Comment by szepeviktor** [comment]
Thank you.

**Comment by greut** [comment]
@szepeviktor hopefully, it'll be working as expected.

**Comment by joachimesque** [comment]
Thank you!
