### ISSUE TITLE
Error: not a git repository

### ISSUE THREAD

**Issue by szepeviktor** [greut/eclint-action#2]
```
E0613 02:27:49.456415      10 main.go:176]  "msg"="cannot list files" "error"="not a git repository: exit status 128"  
E0613 02:27:49.456480      10 main.go:127]  "msg"="linting failure" "error"="not a git repository: exit status 128"  
```

Hello @greut!

Thank you for this action.

Could you help me what am I doing wrong?
https://github.com/szepeviktor/php-path/runs/6854282483?check_suite_focus=true
branch: https://github.com/szepeviktor/php-path/tree/eclint

**Comment by greut** [comment]
@szepeviktor I'll give it a look. Cheers,

**Comment by greut** [comment]
you're missing the checkout.

```yaml
      - name: checkout
        uses: actions/checkout@v3
```

**Comment by szepeviktor** [comment]
Oh nooooooooooooo 😆 

Thank you.

**Comment by szepeviktor** [comment]
After adding that step still

```
E0625 11:36:17.210473      12 main.go:176]  "msg"="cannot list files" "error"="not a git repository: exit status 128"  
E0625 11:36:17.210529      12 main.go:127]  "msg"="linting failure" "error"="not a git repository: exit status 128"  
```

https://github.com/szepeviktor/php-path/runs/7053600124?check_suite_focus=true

**Comment by greut** [comment]
> After adding that step still

it wasn't enough :)

**Comment by szepeviktor** [comment]
We have a colorful output :)

![kép](https://user-images.githubusercontent.com/952007/175772791-10d541ac-025b-4f3b-ba96-7b9563aeae26.png)
